language: scala
before_install:
  - git fetch --tags
stages:
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork
  - name: update-readme
    if: (tag IS present) AND NOT fork
jobs:
  include:
    - stage: release
      scala: 2.12.10
      jdk: openjdk8
      script:
        - sbt ci-release
    - stage: update-readme
      scala: 2.12.10
      jdk: openjdk8
      script:
        - sbt docs/mdoc
        - ./push_readme.sh

cache:
  directories:
  - $HOME/.cache/coursier
  - $HOME/.sbt
  - $HOME/.ivy2
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete -print
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete -print
