language: scala
scala:
  - 2.11.12
  - 2.12.8
  - 2.12.9
  - 2.12.10
  - 2.12.11
  - 2.13.0
  - 2.13.1
  - 2.13.2
jdk:
  - openjdk8
  - openjdk12
cache:
  directories:
  - $HOME/.cache/coursier
  - $HOME/.sbt
  - $HOME/.ivy2
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete -print
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete -print
