sudo: false
language: scala
scala:
  - 2.11.12
  - 2.12.1
  - 2.12.2
  - 2.12.3
  - 2.12.4
  - 2.12.5
  - 2.12.6
  - 2.12.7
  - 2.12.8
  - 2.13.0
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete -print
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete -print
