name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  main:
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        scala:
          - 2.11.12
          - 2.12.12
          - 2.12.13
          - 2.12.14
          - 2.13.0
          - 2.13.1
          - 2.13.2
          - 2.13.3
          - 2.13.4
          - 2.13.5
          - 2.13.6
        java:
          - 1.8
          - 1.11
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@${{ matrix.java }}

      - name: Cache sbt
        uses: coursier/cache-action@v6

      - name: Test
        run: |
          sbt ++${{ matrix.scala }} test
