name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  main:
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        scala:
          - 2.11.12
          - 2.12.12
          - 2.13.0
          - 2.13.1
          - 2.13.2
          - 2.13.3
          - 2.13.4
        java:
          - 1.8
          - 1.11
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@${{ matrix.java }}

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.cache/coursier/v1
          key: sbt-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Test
        run: |
          sbt ++${{ matrix.scala }} test
